Nugine/s3s

- crates/s3s-codegen/src/ops.rs
- crates/s3s/src/ops/generated.rs
> Fix xmlname of root type

- crates/s3s/src/ops/mod.rs
the only places where `create_canonical_request`or `create_presigned_canonical_request` are used, pass in a uri_path wich comes from an `http::uri::Uri` and that already checks that the path is uri encoded.
> do not double uri encode

- codegen/src/aws_conv.rs
- codegen/src/dto.rs
- codegen/src/ops.rs
- codegen/src/rust.rs
- crates/s3s-aws/Cargo.toml
- crates/s3s-aws/src/conv/builtin.rs
- crates/s3s-aws/src/conv/generated.rs
- crates/s3s-aws/src/proxy/generated.rs
- crates/s3s-fs/Cargo.toml
- crates/s3s-fs/src/s3.rs
- crates/s3s-proxy/Cargo.toml
- crates/s3s/src/dto/generated.rs
- crates/s3s/src/dto/mod.rs
- crates/s3s/src/error/generated.rs
- crates/s3s/src/ops/generated.rs
- crates/s3s/src/s3_trait.rs
- scripts/download-model.sh
> aws-sdk-s3 v0.25.1 break change

- .github/workflows/ci.yml
- CONTRIBUTING.md
- crates/s3s-fs/src/main.rs
- crates/s3s-proxy/src/main.rs
- justfile
- scripts/assert-unchanged.sh
- scripts/codegen.sh
- scripts/download-model.py
- scripts/download-model.sh
- scripts/e2e-mint.sh
- scripts/report-mint.py
> Fix E2E test

- crates/s3s-fs/src/fs.rs
- crates/s3s-fs/src/s3.rs
> s3s-fs: verify upload_id

- .github/workflows/ci.yml
- CONTRIBUTING.md
- crates/s3s/src/auth/context.rs
- crates/s3s/src/auth/mod.rs
- crates/s3s/src/ops/mod.rs
- crates/s3s/src/ops/signature.rs
- crates/s3s/src/path.rs
> Access control in S3Auth

- .github/workflows/ci.yml
- CONTRIBUTING.md
- codegen/Cargo.toml
- crates/s3s-aws/Cargo.toml
- crates/s3s-fs/Cargo.toml
- crates/s3s-proxy/Cargo.toml
- crates/s3s/Cargo.toml
- justfile
> Release v0.6.1

- codegen/Cargo.toml
- crates/s3s-aws/Cargo.toml
- crates/s3s-aws/src/error.rs
- crates/s3s-fs/Cargo.toml
- crates/s3s-proxy/Cargo.toml
- crates/s3s-proxy/src/main.rs
- crates/s3s/Cargo.toml
+ https://github.com/awslabs/smithy-rs/releases/tag/release-2023-08-01
+ https://github.com/awslabs/smithy-rs/discussions/2887
+ https://github.com/awslabs/smithy-rs/discussions/2895
+ https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2023-08-03
+ https://github.com/awslabs/aws-sdk-rust/discussions/853
> aws sdk breaking change 2023-08-03

- crates/s3s-fs/Cargo.toml
- crates/s3s-fs/src/checksum.rs
- crates/s3s-fs/src/fs.rs
- crates/s3s-fs/src/lib.rs
- crates/s3s-fs/src/s3.rs
- crates/s3s-fs/src/utils.rs
- crates/s3s-fs/tests/it_aws.rs
- crates/s3s-proxy/Cargo.toml
> s3s-fs checksum support

- codegen/src/ops.rs
- crates/s3s/src/ops/generated.rs
- crates/s3s/src/ops/get_object.rs
> GetObject with Transfer-Encoding

- crates/s3s-fs/src/s3.rs
Implement `upload_part_copy` for the file system crate
> Implement upload_part_copy for s3s_fs

- codegen/src/ops.rs
- crates/s3s/src/ops/generated.rs
> codegen: GetObject range returns 206

- crates/s3s-fs/src/fs.rs
- crates/s3s-fs/src/s3.rs
For multipart uploads the s3-fs server ignored the metadata field. This PR stores the metadata in a temporary file and writes the metadata when the upload is completed.
---
> Store metadata in multipart uploads

- crates/s3s/src/ops/mod.rs
- crates/s3s/src/ops/signature.rs
- crates/s3s/src/path.rs
- crates/s3s/src/sig_v2/methods.rs
- crates/s3s/src/sig_v2/presigned_url_v2.rs
resolves #135 
---
Test (todo in #68)
```bash
npm i aws-sdk
```
```js
import AWS from 'aws-sdk';
var s3 = new AWS.S3({
endpoint: "http://localhost:8014",
region: "us-east-1",
credentials: {
accessKeyId: "minioadmin",
secretAccessKey: "minioadmin"
},
signatureVersion: "v2",
s3ForcePathStyle: true
});
s3.listBuckets((err, data) => {
if (err) console.log(err, err.stack);
else console.log(data);
})
s3.listObjects({ Bucket: "tmp1", Delimiter: "/", Prefix: "" }, (err, data) => {
if (err) console.log(err, err.stack);
else console.log(data);
})
```
> Fix signature v2

- Cargo.toml
- codegen/src/smithy.rs
- crates/s3s-aws/Cargo.toml
- crates/s3s-fs/Cargo.toml
- crates/s3s-proxy/Cargo.toml
- crates/s3s/Cargo.toml
- crates/s3s/src/http/multipart.rs
- crates/s3s/src/ops/signature.rs
- crates/s3s/src/sig_v4/amz_content_sha256.rs
- justfile
> Release v0.10.0

- crates/s3s-fs/Cargo.toml
- crates/s3s-fs/src/checksum.rs
- crates/s3s-fs/src/s3.rs
- crates/s3s/Cargo.toml
- crates/s3s/src/checksum.rs
- crates/s3s/src/lib.rs
> Move ChecksumHasher to s3s

- crates/s3s-fs/Cargo.toml
- crates/s3s-fs/src/main.rs
- crates/s3s-proxy/Cargo.toml
- crates/s3s-proxy/src/main.rs
GracefulShutdown support in hyper_util has been merged an released
https://github.com/hyperium/hyper-util/pull/127
Closes #138
---
> use GracefulShutdown util

- crates/s3s/src/ops/signature.rs
Reading the entire body of an S3 Payload with an `x-amz-content-sha256` header value of `UNSIGNED_PAYLOAD` is not necessary, this PR simply avoids this when possible.
Prior to this, we were reading an entire UNSIGNED_PAYLOAD request into memory, even though this was not required for verification of the signature.
#155 - This doesn't prevent unbounded memory usage in the scenario of `x-amz-content-sha256` being set to the checksum of the body, but it means we don't see unbounded memory usage for the UNSIGNED_PAYLOAD variant.
---
> Prevent Reading Entire Body of UNSIGNED_PAYLOAD Requests During Signature Calculation

- crates/s3s-policy/Cargo.toml
- crates/s3s-policy/src/lib.rs
- crates/s3s-policy/src/model.rs
> feat(s3s-policy): add model

- crates/s3s-fs/src/main.rs
- crates/s3s-fs/tests/it_aws.rs
- crates/s3s-proxy/src/main.rs
- crates/s3s/src/host.rs
- crates/s3s/src/lib.rs
- crates/s3s/src/ops/mod.rs
- crates/s3s/src/ops/signature.rs
- crates/s3s/src/path.rs
- crates/s3s/src/service.rs
> feat(s3s/host): add S3Host

- crates/s3s-fs/src/main.rs
- crates/s3s-fs/tests/it_aws.rs
- crates/s3s-proxy/src/main.rs
- crates/s3s/src/host.rs
- crates/s3s/src/path.rs
- scripts/s3s-fs.sh
- scripts/s3s-proxy.sh
> feat(s3s/host): add MultiDomain

- .github/workflows/ci.yml
- .gitignore
- crates/s3s-test/Cargo.toml
- crates/s3s-test/e2e/main.rs
- crates/s3s-test/src/cli.rs
- crates/s3s-test/src/error.rs
- crates/s3s-test/src/lib.rs
- crates/s3s-test/src/report.rs
- crates/s3s-test/src/runner.rs
- crates/s3s-test/src/tcx.rs
- crates/s3s-test/src/traits.rs
- scripts/e2e-fs.sh
> feat(s3s-test): impl custom test suite

- crates/s3s-test/Cargo.toml
- crates/s3s-test/e2e/main.rs
- crates/s3s-test/src/cli.rs
- crates/s3s-test/src/tcx.rs
> feat(s3s-test): impl filter

- crates/s3s/src/lib.rs
- crates/s3s/src/ops/mod.rs
- crates/s3s/src/route.rs
- crates/s3s/src/service.rs
> feat(s3s/route): support custom route

- crates/s3s/src/ops/signature.rs
> fix(s3s/ops): allow presigned url requests with up to 15 minutes clock skew

- crates/s3s/src/http/request.rs
- crates/s3s/src/ops/mod.rs
- crates/s3s/src/ops/signature.rs
- crates/s3s/src/request.rs
> feat(s3s/ops): forward region & service to S3Request

- crates/s3s/src/ops/mod.rs
- crates/s3s/src/route.rs
> fix(s3s): access check

- codegen/src/v1/dto.rs
- crates/s3s/src/dto/generated.rs
resolves #229 
CC @weisd
```rust
use s3s::dto::DtoExt;
// ...
input.ignore_empty_strings();
```
> feat(s3s/dto): ignore empty strings

- codegen/src/v1/ops.rs
- model/minio-patches.json
> feat(codegen/minio): write to object with specified `versionId`

- Cargo.lock
- crates/s3s/Cargo.toml
- crates/s3s/tests/tokio_util.rs
> test(s3s): tokio_util StreamReader

- Cargo.lock
- crates/s3s/Cargo.toml
- crates/s3s/examples/axum.rs
- crates/s3s/examples/tokio_util.rs
- crates/s3s/src/http/body.rs
- crates/s3s/src/route.rs
> feat(s3s/examples): axum for custom route

- codegen/src/v1/ops.rs
- codegen/src/v1/xml.rs
- crates/s3s/src/xml/generated.rs
- crates/s3s/src/xml/mod.rs
- crates/s3s/src/xml/ser.rs
- crates/s3s/tests/xml.rs
> feat(s3s/xml): support xmlns

- Cargo.lock
- codegen/Cargo.toml
- crates/s3s-aws/Cargo.toml
- crates/s3s-e2e/Cargo.toml
- crates/s3s-fs/Cargo.toml
- crates/s3s-model/Cargo.toml
- crates/s3s-policy/Cargo.toml
- crates/s3s-proxy/Cargo.toml
- crates/s3s-test/Cargo.toml
- crates/s3s/Cargo.toml
- crates/s3s/src/utils/crypto.rs
Related:
+ https://github.com/Nugine/s3s/issues/268
> build(deps): downgrade hashes

- Cargo.lock
- Cargo.toml
- crates/s3s-fs/Cargo.toml
- crates/s3s/Cargo.toml
- crates/s3s/src/checksum.rs
- crates/s3s/src/utils/crypto.rs
> feat(s3s/crypto): use latest RustCrypto releases

- Cargo.lock
- Cargo.toml
- crates/s3s-fs/Cargo.toml
- crates/s3s-fs/src/fs.rs
- crates/s3s-fs/src/s3.rs
- crates/s3s/Cargo.toml
- crates/s3s/src/checksum.rs
- crates/s3s/src/crypto.rs
- crates/s3s/src/lib.rs
> feat(s3s/crypto): extract checksum algorithms

- crates/s3s/src/http/ordered_headers.rs
- crates/s3s/src/ops/signature.rs
- crates/s3s/src/sig_v4/methods.rs
> fix(s3s/signature): host header fallback on HTTP2

- .github/copilot-instructions.md
- .github/workflows/ci.yml
- CONTRIBUTING.md
- Cargo.lock
- Cargo.toml
- codegen/Cargo.toml
- crates/s3s-aws/Cargo.toml
- crates/s3s-e2e/Cargo.toml
- crates/s3s-fs/Cargo.toml
- crates/s3s-model/Cargo.toml
- crates/s3s-policy/Cargo.toml
- crates/s3s-proxy/Cargo.toml
- crates/s3s-test/Cargo.toml
- crates/s3s-test/src/runner.rs
- crates/s3s/Cargo.toml
- crates/s3s/src/service.rs
> build(deps): upgrade

- Cargo.lock
- codegen/src/v1/ops.rs
- crates/s3s-e2e/Cargo.toml
- crates/s3s-e2e/src/basic.rs
- crates/s3s-fs/src/s3.rs
- crates/s3s/src/http/aws_chunked_stream.rs
- crates/s3s/src/http/de.rs
- crates/s3s/src/http/request.rs
- crates/s3s/src/lib.rs
- crates/s3s/src/ops/generated.rs
- crates/s3s/src/ops/mod.rs
- crates/s3s/src/ops/signature.rs
- crates/s3s/src/protocol.rs
- crates/s3s/src/sig_v4/amz_content_sha256.rs
- crates/s3s/src/sig_v4/methods.rs
- scripts/install.py
> feat(s3s): support streaming trailers
