Nugine/s3s

.github/workflows/ci.yml
crates/s3s-fs/Cargo.toml

Windows Build Fixes
* Allows `s3s-fs` to build on Windows MSVC by removing dependency the `md-5/asm` feature which has an upstream bug.
* Add Windows and MacOS CI jobs.
Closes https://github.com/Nugine/s3s/issues/52
----------------------
_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

Fix Windows build and improve CI

---

crates/s3s-fs/src/s3.rs

This PR implement `list_parts` for the file system crate. I also ended up fixing a bug for the copy_object operation (dst object directory not created)
---

Implement list_parts for s3s-fs

---

crates/s3s-fs/src/s3.rs

There's a bug in copy_object that if the destination contains "/", it will fail to copy because the directories were not created.

s3s-fs: create dir on copy_object

---

crates/s3s-fs/src/s3.rs

Implement `abort_multipart_upload` for the file system crate

Implement abort_multipart_upload for s3s_fs

---

crates/s3s/src/ops/signature.rs

In the absence of payload signing, the `x-amz-content-sha256` header may contain the 'UNSIGNED-PAYLOAD' value.
---

Support UNSIGNED-PAYLOAD for AWS SigV4 requests

---

crates/s3s-fs/src/s3.rs

This commit adds support for `start_after` and fixes some issues with `Path::start_with` being more strict than `str::start_with`.

s3s-fs: fix path matching and add start_after

---

crates/s3s-fs/src/fs.rs
crates/s3s-fs/src/s3.rs

I've noticed that occasionally put object requests would result in empty or partially written objects.
After a bit of debugging this turned out to be cases where the S3 client or `s3s-fs` was interrupted/killed mid-upload.
The current implementation writes directly to the final destination, which can cause partial writes.
This PR writes to a temporary file path first, then moves to the final location.
This should also take care of cases when the `s3s-fs` was killed abruptly mid-write.
To handle this, there's also a start-up clean-up of any leftover outstanding partially written files.
---

s3s-fs: fix incomplete uploads by writing via a temp file

---

crates/s3s-fs/src/fs.rs
crates/s3s-fs/src/s3.rs

Following on from https://github.com/Nugine/s3s/pull/116, this PR introduces the use of temp files for multipart uploads as well. This is to improve consistency of writes.
With this change, all file writes are now performed via a temporary file first which is then renamed to its final location.
---

s3s-fs: fix consistency of multipart uploads via a temp file

---

crates/s3s-fs/src/s3.rs
crates/s3s/src/dto/range.rs

[RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html#name-range-specifiers) states:
*A valid ranges-specifier is "satisfiable" if it contains at least one range-spec that is satisfiable, as defined by the indicated range-unit. Otherwise, the ranges-specifier is "unsatisfiable".*
Thus, one may not reject a range request that exceeds file length. This PR allows for requesting a too long range from s3-fs, which will silently be cropped to maximum length. This also matches the functionality of Minio and [Rados gateway](https://github.com/ceph/ceph/blob/f265c99628651ed291fe2f6a63483cc971fd0a82/src/rgw/rgw_sal.cc#L441).
Furthermore, the Content-Range header is filled in accordance to RFC 9110.
---
*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …

Fix range requests for GetObject

---

crates/s3s/Cargo.toml
crates/s3s/src/sig_v4/methods.rs
crates/s3s/src/utils/crypto.rs

Changing the sha2 implementation to openssl may increase the speed tremendously. On a Cascade Lake Xeon we saw 60% increase in PUT performance. As openssl may not be a good choice in every situation, it is capsuled in a cargo feature.
The `unwraps` may be not wanted, but avoiding them would change the function signature.
WARP before:
----------------------------------------
Operation: PUT. Concurrency: 20
* Average:216.98 MiB/s, 21.70 obj/s
Throughput, split into 111 x 1s:
* Fastest:244.7MiB/s, 24.47 obj/s
* 50% Median:217.6MiB/s, 21.76 obj/s
* Slowest:193.1MiB/s, 19.31 obj/s
WARP after:
----------------------------------------
Operation: PUT. Concurrency: 20
* Average:354.65 MiB/s, 35.46 obj/s
Throughput, split into 65 x 1s:
* Fastest:377.3MiB/s, 37.73 obj/s
* 50% Median:355.9MiB/s, …

Added Openssl feature

---

crates/s3s/src/ops/mod.rs

request with an ip address host cannot use virtual-hosted-style
---

always parse path style request for non domain hosts

---

crates/s3s/src/ops/mod.rs

in  #147 it only checks for SocketAddr wich donnot parse ip addresses without a port. this fixes that
---

fix always parse path style request for non domain hosts

---

codegen/src/ops.rs
crates/s3s/Cargo.toml
crates/s3s/src/http/ser.rs
crates/s3s/src/keep_alive_body.rs
crates/s3s/src/lib.rs
crates/s3s/src/ops/generated.rs
crates/s3s/src/ops/mod.rs
crates/s3s/src/ops/tests.rs

reopen of #31
> changes the response body from the CompleteMultipartUpload Operation to a custom KeepAliveBody that sends a whitespace every 100 milliseconds to keep the request alive
but now with hyper support for trailers
fixes  #30
---

keep CompleteMultipartUpload alive

---

crates/s3s/Cargo.toml
crates/s3s/src/service.rs

- add optional feature  `tower` which implements the [tower::Service](https://docs.rs/tower/latest/tower/trait.Service.html) trait. 
- allows using tower middleware like CORS for https://github.com/Nugine/s3s/issues/144.

Add tower feature

---

crates/s3s/src/error/mod.rs
crates/s3s/src/ops/mod.rs
crates/s3s/src/ops/signature.rs

As part of work I have done recently to prevent un-bounded memory growth in s3s, I put a basic middleware in front of my service that checks the signature mechanism and content-length, denying requests that will incur massive memory usage.
In doing this, I realized I would need to write my own serialization to send the error response using Hyper. This PR exposes the internal `serialize_error` method so it can used in consumer's middleware.
I was not quite sure how you would prefer this to be exposed / if you think this is a good idea at all. Let me know your thoughts / suggestions.
```rust
impl Service<hyper::Request<hyper::body::Incoming>> for PreCheck {
type Response = hyper::Response<Body>;
type Error = S3Error;
type Future = BoxFuture<'static, Result<Self::Response, Self::Error>>;
fn …
```

Expose Error Serialization To Consumers to Allow Ergnomoic Middleware

---

crates/s3s-aws/src/connector.rs
crates/s3s-fs/src/main.rs
crates/s3s-fs/tests/it_aws.rs
crates/s3s-proxy/src/main.rs
crates/s3s/Cargo.toml
crates/s3s/src/error/mod.rs
crates/s3s/src/http/request.rs
crates/s3s/src/http/response.rs
crates/s3s/src/lib.rs
crates/s3s/src/protocol.rs
crates/s3s/src/service.rs
crates/s3s/src/sig_v4/methods.rs

+ Remove `tower` feature and make it default
+ Remove `MakeService` and `SharedS3Service`
+ Make `S3Service` shared
+ Changes around http types (`HttpRequest`, `HttpResponse`, `HttpError`)
Related
+ #210

refactor S3Service and http types

---

crates/s3s-fs/src/s3.rs
crates/s3s-fs/tests/it_aws.rs

This PR applies the patch for the range fix to branch 0.9.
I can't build it locally, but I don't see anything about the commit that would break the build. Seems this part of the code hasn't changed too much since 0.9. 
* Fix checksum for range
This fixes the checksum behavior for range to line up with S3's implementation. S3 will only return checksums if the range is large enough that the entire file is returned, otherwise they get skipped.

fix(s3s-fs): fix checksum for range 0.9 patch (#285)

---

Cargo.lock
crates/s3s/Cargo.toml
crates/s3s/src/auth/secret_key.rs

and replace it with ConstantTimeEq.
It seems to have no effect on the s3s codebase itself, but it is a breaking change for users of the `s3s` crate. On the other hand, relying on the previous PartialEq implementation is almost never a safe thing to do.

Remove non-constant time PartialEq impl from SecretKey

---

Cargo.lock
codegen/Cargo.toml
crates/s3s-test/Cargo.toml
crates/s3s/Cargo.toml

Getting some upstream yanked dependency issue with `nugine-rust-utils`. I see it's not used so this PR removes it.

remove unnecessary yanked dependencies

---

crates/s3s-fs/tests/it_aws.rs
crates/s3s/src/lib.rs
crates/s3s/src/ops/mod.rs
crates/s3s/src/path.rs
crates/s3s/src/service.rs
crates/s3s/src/validation.rs

Adds an optional validation API for S3 bucket names, allowing custom rules while keeping AWS-compliant defaults.
**Changes**
- New NameValidation trait for custom bucket name validation
- DefaultNameValidation keeps the existing functionality, no change
- S3ServiceBuilder::set_validation() to configure custom validation
- Backward compatible, existing code uses default validation

Add custom validation option to S3ServiceBuilder
